name: Publish to Docker Hub stage

on:
  pull_request:
    branches:
      - main

jobs:
 docker-image-CI:
   name: Docker Image CI
   runs-on: ubuntu-latest
   steps:

    - name: Check out git repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v9

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      if: steps.branch-name.outputs.is_default == 'false'
      id: docker_build
      uses: docker/build-push-action@v6
      with:
         context: ./
         file: ./Dockerfile
         provenance: mode=max
         sbom: true
         push: true
         tags: "clinicalgenomics/tip2toe-stage:${{steps.branch-name.outputs.current_branch}}, clinicalgenomics/tip2toe-stage:latest"
