name: Publish to Docker Hub stage

on:
  pull_request:
    branches:
      - main

jobs:
 docker-image-CI:
   name: Docker Image CI
   runs-on: ubuntu-latest
   steps:

    - name: Check out git repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Publish main image (Dockerfile) to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: clinicalgenomics/tip2toe-stage
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile-stage
        tags: "latest, ${{steps.branch-name.outputs.current_branch}}"
